// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC288-mo95OZ1grmqKYEpmHA0bXkpOhtk',
    appId: '1:126240976759:web:c50c105e8f8754736dbb72',
    messagingSenderId: '126240976759',
    projectId: 'ecs198f-flutter-firebase-demo',
    authDomain: 'ecs198f-flutter-firebase-demo.firebaseapp.com',
    storageBucket: 'ecs198f-flutter-firebase-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvCqyVLGEw1FKcg9s-VRo_hKkF85jLLs',
    appId: '1:126240976759:android:a7903193eb69ba316dbb72',
    messagingSenderId: '126240976759',
    projectId: 'ecs198f-flutter-firebase-demo',
    storageBucket: 'ecs198f-flutter-firebase-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO3F3Olxc2IGHdsth-olk1ql4B2_0beKY',
    appId: '1:126240976759:ios:e1a9185efcec4a416dbb72',
    messagingSenderId: '126240976759',
    projectId: 'ecs198f-flutter-firebase-demo',
    storageBucket: 'ecs198f-flutter-firebase-demo.appspot.com',
    androidClientId: '126240976759-rotncvj4o8jmna1qd3m4g9jg35728t1a.apps.googleusercontent.com',
    iosClientId: '126240976759-4di1eme94ghfildc9resk42908vhegt4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
}
